config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'

  resources :questions, shallow: true do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :question

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :answers, dependent: :destroy

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers

  def author_of?(obj)
    id == obj&.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  expose :answer
  expose :question, -> { @question ||= params[:question_id] ? Question.find(params[:question_id]) : answer.question }

  def create
    answer.question = question
    answer.author = current_user
    if answer.save
      redirect_to question_path(answer.question)
    else
      render 'questions/show'
    end
  end

  def destroy
    if current_user.author_of?(answer)
      answer.destroy
      redirect_to answer.question
    else
      redirect_to answer.question, notice: 'You don`t have permission to delete this answer.'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  expose :questions, -> { Question.all }
  expose :question

  def create
    question.author = current_user
    if question.save
      redirect_to question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def destroy
    if current_user.author_of?(question)
      question.destroy
      redirect_to questions_path
    else
      flash.now[:notice] = 'You don`t have permission to delete this question.'
      render :show
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def answer
    @answer ||= question.answers.new(author: current_user)
  end

  helper_method :answer
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
li
  = "#{answer.body} "
  -if current_user&.author_of?(answer)
    = link_to ' Delete answer ', answer_path(answer), method: :delete, data: { confirm: 'Delete this answer?', title: 'Delete answer' }

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  body

    - if user_signed_in?
      sli= link_to "Sign out", destroy_user_session_path, method: :delete
    - else
      sli= link_to "Sign in", new_user_session_path

    p class=notice = notice
    p class=alert = alert

    = yield

app/views/questions/_question.html.slim
li= link_to "#{question.title}", question_path(question)

app/views/questions/index.html.slim
b= "Questions: "
ul
  = render questions

p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

= form_with model: question, local: true do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.submit 'Ask'

app/views/questions/show.html.slim
h1= question.title
p= question.body

-if current_user&.author_of?(question)
    = link_to 'Delete question', question_path(question), method: :delete, data: { confirm: 'Delete this question?' }

ul
  = render question.answers

= render 'shared/errors', resource: answer
= form_with model: [question, answer], local: true do |f|
  = f.label :body, 'Give your answer:'
  = f.text_area :body
  = f.submit 'Post answer'

app/views/shared/_errors.html.slim
-if resource&.errors.present?
  b= "#{resource.class} #{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message